
openapi: 3.0.0
info:
  title: Script Execution Service
  version: 1.0.0
paths:
  /execute:
    post:
      summary: Execute a script
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                scriptId:
                  type: string
      responses:
        '200':
          description: Execution result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
components:
  schemas:
    ExecutionResult:
      type: object
      properties:
        output:
          type: string
        error:
          type: string
        duration:
          type: number
